spring:
  application:
    name: rocketmq-consumer

server:
  port: 8084

rocketmq:
  name-server: 10.238.248.14:9876
  consumer:
    #    group: my-producer-group
    #    #目的地（topic:tag）
    #    #topic
    #    topic: anran-topic
    #组名
    group: anran-consumer-group
    #监听主题
    topic: anran-topic
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）
    tags: anran-sync-tags||anran-async-tags||anran-oneway-tags
